### ISSUE TITLE
Global name Re not defined - Python version problem?

### ISSUE THREAD

**Issue by skogler** [sven-strothoff/vim-clang_doxygen#2]
Does not work for me due to some python problem (see the error below).
I tried just writing import re at the top, which avoids the error. Then, I get 
    Error: No supported declaration found at ...

Clang: 3.2
Vim: 7.3 with +python -python3

``` ...
File "~/.vim/bundle/vim-clang_doxygen/plugin/clang_doxygen.py", line 205, in
generateDoxygenForSourceLocation
    indent = re.match(r'^\s*', vim.current.buffer[line - 1]).span()[1]
NameError: global name 're' is not defined
```

This plugin seems really useful, could you help me with this?

**Comment by jupbarrera** [comment]
Same problem here. I didn't get the re problem error. But I get the no supported declaration found at ...
